### ISSUE TITLE
Есть ли возможность избавиться от избыточных комментариев по всему коду? (Пример на скриншоте)

### ISSUE THREAD

**Issue by BaggerFast** [DashaIgnatieva/CalorieCalculatorBot#1]
![image](https://github.com/DashaIgnatieva/CalorieCalculatorBot/assets/54527361/f5852ca0-0d72-447b-be72-7ab527006156)

**Comment by DashaIgnatieva** [comment]
Да, я как раз хотела этим заняться, привести все в нормальный вид)

**Comment by BaggerFast** [comment]
Ок, ждемс
